### PR TITLE
Forces locale to en for keytool list

### LINKED ISSUE #446: Extra colon and space in assetlinks.json
Hi everyone
First of all, I would like to thank you for this great tool!

**Describe the bug**
When I run `bubblewrap build --skipPwaValidation`, it generates the `assetlinks.json` file well, but it adds a colon followed by a space at the beginning of the `sha256_cert_fingerprints`.
I have to remove it manually, otherwise the correspondence between the application and assetlinks is not ok.

**Output example:**
`"sha256_cert_fingerprints": [": 85:A0...`

**Expected output example:**
`"sha256_cert_fingerprints": ["85:A0...`

**Steps to reproduce:**
- `bubblewrap init --manifest=https://thewebsite`
- `bubblewrap build --skipPwaValidation`

**Environment**
- macOS Mojave version 10.14.5.
- @bubblewrap/cli@1.8.2
- node v10.20.0
- `"jdkPath":"/Users/username/.bubblewrap/jdk/jdk8u265-b01"`
- `"androidSdkPath":"/Users/username/.bubblewrap/android_sdk"`

### PR DESCRIPTION
**Pull request by andreban**
Fixes #446

### CODE REVIEW

**Review by cdreydemy-vp — APPROVED** [review]

File: packages/core/src/lib/jdk/KeyTool.ts [hunk 1]
```diff
@@ -100,6 +100,11 @@ export class KeyTool {
     }
     const keyListCmd = [
       'keytool',
+      // Forces the language to 'en' in order to get the expected formatting.
+      // The JVM seems to ignore the LANG and LC_ALL variables, so we set the value
```
Comment (PEConn) [inline packages/core/src/lib/jdk/KeyTool.ts:104]: I'm assuming the JVM wants something that is consistent across OSes? (Do `LANG` and `LC_ALL` exist on Windows?)

**Review by PEConn — APPROVED** [review]

File: packages/core/src/lib/jdk/KeyTool.ts (hunk 1 above)
Comment (andreban) [reply packages/core/src/lib/jdk/KeyTool.ts:104]: It seems `LANG` does exist on Windows. Nevertheless, this seems to the the appropriate way to do this.
