### PR TITLE
Escape gradle string in shareTarget / build.gradle

### LINKED ISSUE #673: Share Target with single quote throws an error
The [issue](https://github.com/pwa-builder/PWABuilder/issues/2812) was raised on the [PWABuilder](https://pwabuilder.com/) repo. We use bubblewrap to package TWAs. It seems to throw the following error every time we try to create a package, and it's due to the french characters being used in the apps manifest, specifically in the description:

> "description": "La Chorale de Cocody Philadelphie est une chorale l'Eglise Adventiste du 7ième jour de Cocody Philadelphie. Elle chante pour la gloire de DIEU et pour gagner des âmes à Christ.",

cli ERROR Command failed: gradlew.bat assembleRelease --stacktrace

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\jaylynbarbee\OneDrive - Microsoft\Desktop\bbwrap-test\app\build.gradle' line: 80

* What went wrong:
Could not compile build file 'C:\Users\jaylynbarbee\OneDrive - Microsoft\Desktop\bbwrap-test\app\build.gradle'.
> startup failed:
build file 'C:\Users\jaylynbarbee\OneDrive - Microsoft\Desktop\bbwrap-test\app\build.gradle': 80: unexpected char: '\' @ line 80, column 430.
pour gagner des �mes � Christ.\\",\\"url

**To Reproduce**
1. bubblewrap init --manifest https://adventiste-ccp.web.app/manifest.webmanifest
2. bubblewrap build

**Expected behavior**
Package generated with no error.

### PR DESCRIPTION
**Pull request by andreban**
Escapes the gradle string before escaping the JSON. This ensures single quotes
are escaped.

Fixes #673

### CODE REVIEW

**Review by PEConn — COMMENTED** [review]
Where does this method come from? I can't find the docs for it.

I feel uneasy about escaping a string twice - how do we know this won't do something crazy?

**Comment by andreban** [comment]
It's set here: https://github.com/GoogleChromeLabs/bubblewrap/blob/main/packages/core/src/lib/TwaGenerator.ts#L404

**Comment by PEConn** [comment]
Yeah, that would be good, thanks.

**Comment by andreban** [comment]
> Yeah, that would be good, thanks.

Added a test. PTAL

File: packages/core/src/spec/lib/utilSpec.ts [hunk 1]
```diff
@@ -304,4 +304,16 @@ describe('util', () => {
           .toEqual('\\"\\$Hello\\\\Wo\\`eld\\"');
     });
   });
+
+  describe('#escapeJsonString combined with #escapeGradleString returns the expected results',
+      () => {
+        it('Escapes double and single quotes', () => {
+          // String.raw prevents escape characters from being applied, so we can simplify howe we write
```
Comment (PEConn) [inline packages/core/src/spec/lib/utilSpec.ts:311]: nit: typo on "how"

**Review by PEConn — APPROVED** [review]
LGTM % nit thanks

File: packages/core/src/spec/lib/utilSpec.ts (hunk 1 above)
Comment (andreban) [reply packages/core/src/spec/lib/utilSpec.ts]: fixed
